config/routes.rb
SampleApp::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :animes

  root  'static_pages#home'
  match '/signup',    to: 'users#new',            via: 'get'
  match '/signin',    to: 'sessions#new',         via: 'get'
  match '/signout',   to: 'sessions#destroy',     via: 'delete'
  match '/help',      to: 'static_pages#help',    via: 'get'
  match '/about',     to: 'static_pages#about',   via: 'get'
  match '/contact',   to: 'static_pages#contact', via: 'get'
  match '/add',       to: 'animes#new',           via: 'get'
  match '/edit',      to: 'users#edit',           via: 'get'
  match '/animes',    to: 'animes#index',         via: 'get'
  match '/users',     to: 'users#index',          via: 'get'
  match '/search',    to: 'animes#search',           via: 'get'
  match '/delete',    to: 'animes#destroy',       via: 'delete'

end

app/models/anime.rb
class Anime < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :animes
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, 
						uniqueness: { case_sensitive: false }
	has_secure_password
	before_save { email.downcase! }
	validates :password, length: { minimum: 6 }

	def User.new_remember_token
    	SecureRandom.urlsafe_base64
  	end

	def User.encrypt(token)
	    Digest::SHA1.hexdigest(token.to_s)
	end

  	private

	    def create_remember_token
	      self.remember_token = User.encrypt(User.new_remember_token)
	    end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController

	def show
		@anime = Anime.find(params[:id])
	end

	def new
		@anime = Anime.new
	end

	def index
		@anime_list = current_user.animes
	end

	def create
		@anime = Anime.new(anime_params)
		@anime.user = current_user
		if @anime.save
			flash[:success] = "Anime successfully added!"
			redirect_to @anime
		else
			render 'new'
		end
	end

	def destroy
		Anime.find(params[:id]).destroy
		flash[:success] = "Anime deleted."
		redirect_to '/animes'
	end

	def search
	end

	private

		def anime_params
			params.require(:anime).permit(:name, :score, :progress)
		end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  before_filter :require_login

	private

	  def require_login
	    unless current_user
	    flash[:notice] = "Please sign in."
	      redirect_to '/signin'
	    end
	  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
  skip_before_filter :require_login
  
  def new
      if current_user
        redirect_to '/'
      end
  end

  def create
  	  user = User.find_by(email: params[:session][:email].downcase)
  	  if user && user.authenticate(params[:session][:password])
  	      sign_in user
  	      redirect_to user
  	  else
  	      flash.now[:error] = 'Invalid email/password combination'
  	      render 'new'
      end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	skip_before_filter :require_login
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  skip_before_filter :require_login

	def show
    	@user = User.find(params[:id])
  end

  def new
    if current_user
      redirect_to '/'
    else
      @user = User.new
    end
  end

  def index
    @user = current_user
    if current_user.admin?
      @users = User.paginate(page: params[:page])
    else
      flash[:error] = "You've no rights for viewing this page"
      redirect_to @user
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
 		   flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Successfully updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    if !@user.admin?
      @user.destroy
      flash[:success] = "User deleted."
      redirect_to users_url  
    else
      flash[:success] = "You can't delete the administrator."
      redirect_to users_url
    end

  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/anime_helper.rb
module AnimeHelper
end

app/helpers/anime_lists_helper.rb
module AnimeListsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    remember_token = User.encrypt(cookies[:remember_token])
    @current_user ||= User.find_by(remember_token: remember_token)
  end

  def sign_out
    current_user.update_attribute(:remember_token,
                                  User.encrypt(User.new_remember_token))
    cookies.delete(:remember_token)
    self.current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/animes/anime_search.html.erb
<% provide(:title, 'Anime search') %>
<h1>Anime search</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@anime) do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Search", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/animes/index.html.erb
<% provide(:title, 'My animes') %>
<h1>My animes</h1>

<ul class="animes">
  <% @anime_list.each do |anime| %>
	<li>
	  <%= link_to anime.name, anime %>
	  <% if !current_user.nil? %>
	    | <%= link_to "delete", anime, method: :delete,
	                                  data: { confirm: "You sure?" } %>
	  <% end %>
	</li>
	  <% end %>
</ul>

app/views/animes/new.html.erb
<% provide(:title, 'Add anime') %>
<h1>Add anime</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@anime) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :score %>
      <%= f.number_field :score %>

      <%= f.label :progress %>
      <%= f.number_field :progress %>


      <%= f.submit "Add new anime", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/animes/search.html.erb
<% provide(:title, 'Search') %>
<h1>Search</h1>


<div class="row">
  <div class="span6 offset3">
    <%= form_for(@anime) do |f| %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.submit "Search", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/animes/show.html.erb
<% provide(:title, @anime.name) %>

<ul class="anime">
    <h2>
      <%= @anime.name %>
    </h2>
        <li>Score:
      <%= @anime.score %>
    </li>
        <li>Progress:
      <%= @anime.progress %>
    </li>
</ul>

<%= link_to "Delete", delete_path, method: "delete" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="https://github.com/mellhime/sample_app">Test App</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "AnimeList", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">

          <% if signed_in? %>
            
             <li><%= link_to "Add Anime", add_path %></li>
             <li><%= link_to "My Animes", animes_path %></li>
             <li><%= link_to "Search", '#' %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Edit profile", edit_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>

               <% if current_user.admin? %>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Adminka <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Users", users_path %></li>
              </ul>
            </li>
                <% end %>

          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "alert alert-#{key}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  The <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
  is a project to make a book and screencasts to teach web development
  with <a href="http://rubyonrails.org/">Ruby on Rails</a>. This
  is the sample application for the tutorial.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact Ruby on Rails Tutorial about the sample app at the
  	<a href="http://railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://railstutorial.org/book">Rails Tutorial book</a>.
</p>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Welcome to the Sample App</h1>

  <h2>
    This is the home page for the
    <a href="http://railstutorial.org/">Ruby on Rails Tutorial</a>
    sample application.
  </h2>

  <%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/' %>

app/views/users/edit.html.erb
<% provide(:title, 'Edit') %>
<h1>Edit</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
    <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Edit my account", class: "btn btn-large btn-primary" %>
    <% end %>

      <%= gravatar_for @user %>
    <a href="http://gravatar.com/emails">change</a>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<ul class="users">
  <% @users.each do |user| %>
<li>
  <%= gravatar_for user, size: 52 %>
  <%= link_to user.name, user %>
  <% if current_user.admin? %>
    | <%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
  <% end %>
</li>
  <% end %>
</ul>

<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
     <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>

  <ul class="user">
    <li>
      <%= @user.name %>
      
    </li>
        <li>
      <%= @user.email %>
    </li>
</ul>

</div>